---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dino-park-profile-publisher-deployment
  namespace: dino-park
  labels:
    app: dino-park-profile-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dino-park-profile-publisher
  template:
    metadata:
      labels:
        app: dino-park-profile-publisher
    spec:
      containers:
        - name: dino-park-profile-publisher
          image: mozillaparsys/dino-park-profile-publisher:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: SHUTDOWN_TIMEOUT
              value: "1000"
            - name: CIS_UPDATE_URL
              value: "http://dino-cave/cisUpdate"
            - name: CIS_STATUS_URL
              value: "http://dino-cave/cisStatus/"
            - name: CIS_STATUS_TIMEOUT
              value: "1000"
            - name: CIS_STATUS_RETRY_DELAY
              value: "100"
            - name: CIS_STATUS_RETRY_COUNT
              value: "10"
            - name: PERSON_API_URL
              value: "http://dino-cave/personApi/"
            - name: ORGCHART_API_URL
              value: "http://dino-tree/update"
            - name: SEARCH_API_URL
              value: "http://dino-park-search/update"